name: Run Main Script

on:
  schedule:
    - cron: "0 6 * * *" # 6:00 AM UTC / 3:00 AM GMT-3
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCLOUD_WIF_PROVIDER }}
          service_account: ${{ vars.GDRIVE_TARGET_SERVICE_ACCOUNT }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run Python script
        env:
          GDRIVE_FOLDER_ID: ${{ vars.GDRIVE_FOLDER_ID }}
          GDRIVE_TARGET_SERVICE_ACCOUNT: ${{ vars.GDRIVE_TARGET_SERVICE_ACCOUNT }}
          TDP_API_KEY: ${{ vars.TDP_API_KEY }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ vars.SUPABASE_SECRET_KEY }}
          START_DATE: ${{ vars.START_DATE }}
          IGNORED_CLIENT_NUMBERS: ${{ vars.IGNORED_CLIENT_NUMBERS }}
        run: uv run src/main.py
